/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ac.cr.uned.nutrimind.vistas;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 *
 */
public class Admin_vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_vista.class.getName());

    /**
     * Creates new form Admin_vista
     */
    public Admin_vista() {
        initComponents();
        
        ImageIcon label_icon = new ImageIcon(getClass().getResource("/ac/cr/uned/nutrimind/resources/nutrimind_logo.png"));
        Image scaledImage = label_icon.getImage().getScaledInstance(
        admin_lbl.getWidth(), 
        admin_lbl.getHeight(), 
        Image.SCALE_SMOOTH
    );
        admin_lbl.setIcon(new ImageIcon(scaledImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_lbl = new javax.swing.JLabel();
        bienvenida_lbl = new javax.swing.JLabel();
        buscar_paciente_btn = new javax.swing.JButton();
        historial_btn = new javax.swing.JButton();
        agregar_paciente_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        admin_lbl.setText("Imagen");

        bienvenida_lbl.setText("Bienvenido/a Administrador");

        buscar_paciente_btn.setText("Buscar Paciente");
        buscar_paciente_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_paciente_btnActionPerformed(evt);
            }
        });

        historial_btn.setText("Historial Nutricional");
        historial_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historial_btnActionPerformed(evt);
            }
        });

        agregar_paciente_btn1.setText("Agregar Paciente");
        agregar_paciente_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_paciente_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(agregar_paciente_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(buscar_paciente_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(historial_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(admin_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(bienvenida_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(bienvenida_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(admin_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historial_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar_paciente_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_paciente_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar_paciente_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_paciente_btnActionPerformed
        // TODO add your handling code here:
        
        SwingUtilities.invokeLater(() -> {
            
            Buscar_paciente_vista buscarPacienteWindow = new Buscar_paciente_vista();
            buscarPacienteWindow.setLocationRelativeTo(null);
            buscarPacienteWindow.setResizable(false);
            buscarPacienteWindow.setVisible(true);
        });
    }//GEN-LAST:event_buscar_paciente_btnActionPerformed

    private void agregar_paciente_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_paciente_btn1ActionPerformed
        // TODO add your handling code here:
        
        SwingUtilities.invokeLater(() -> {
            
            Agrega_paciente_vista agregarPacienteWindow = new Agrega_paciente_vista(1);
            agregarPacienteWindow.setLocationRelativeTo(null);
            agregarPacienteWindow.setResizable(false);
            agregarPacienteWindow.setVisible(true);
        });
    }//GEN-LAST:event_agregar_paciente_btn1ActionPerformed

    private void historial_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historial_btnActionPerformed

        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            
            Historial_vista historialWindow = new Historial_vista();
            historialWindow.setLocationRelativeTo(null);
            historialWindow.setResizable(false);
            historialWindow.setVisible(true);
        });
    }//GEN-LAST:event_historial_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_lbl;
    private javax.swing.JButton agregar_paciente_btn1;
    private javax.swing.JLabel bienvenida_lbl;
    private javax.swing.JButton buscar_paciente_btn;
    private javax.swing.JButton historial_btn;
    // End of variables declaration//GEN-END:variables
}
