/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ac.cr.uned.nutrimind.vistas;

import ac.cr.uned.nutrimind.modelos.Evaluacion;
import ac.cr.uned.nutrimind.modelos.Paciente;
import ac.cr.uned.nutrimind.resources.DatabaseManager;
import java.math.BigDecimal;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class Agrega_paciente_vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Agrega_paciente_vista.class.getName());

    /**
     * Creates new form Agrega_paciente_vista
     */
    public Agrega_paciente_vista(int rol) {
        this.rol = rol; 
        initComponents();
    }

    Agrega_paciente_vista() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar_pac_lbl = new javax.swing.JLabel();
        id_lbl = new javax.swing.JLabel();
        apellidos_txt = new javax.swing.JTextField();
        nombre_lbl = new javax.swing.JLabel();
        id_txt1 = new javax.swing.JTextField();
        apellidos_lbl = new javax.swing.JLabel();
        nombre_txt1 = new javax.swing.JTextField();
        fecha_nac_lbl = new javax.swing.JLabel();
        fecha_nac_txt = new javax.swing.JFormattedTextField();
        sexo_lbl = new javax.swing.JLabel();
        sexo_cmbbox = new javax.swing.JComboBox<>();
        fecha_reg_lbl = new javax.swing.JLabel();
        fecha_reg_txt = new javax.swing.JFormattedTextField();
        agregar_btn = new javax.swing.JButton();
        peso_lbl = new javax.swing.JLabel();
        altura_txt = new javax.swing.JTextField();
        altura_lbl = new javax.swing.JLabel();
        peso_txt1 = new javax.swing.JTextField();
        nivel_act_fis_lbl = new javax.swing.JLabel();
        nivel_act_fis_cmbbox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        agregar_pac_lbl.setText("Agregar Paciente");

        id_lbl.setText("Identificación:");

        nombre_lbl.setText("Nombre: ");

        apellidos_lbl.setText("Apellidos:");

        fecha_nac_lbl.setText("Fecha Nacimiento: ");

        fecha_nac_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        sexo_lbl.setText("Sexo: ");

        sexo_cmbbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", " " }));

        fecha_reg_lbl.setText("Fecha Registro: ");

        fecha_reg_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        agregar_btn.setText("Agregar Paciente");
        agregar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_btnActionPerformed(evt);
            }
        });

        peso_lbl.setText("Peso (kg): ");

        altura_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altura_txtActionPerformed(evt);
            }
        });

        altura_lbl.setText("Altura (cm):");

        nivel_act_fis_lbl.setText("Nivel Actividad Fisica:");

        nivel_act_fis_cmbbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentario", "Moderadamente Activo", "Muy Activo", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellidos_lbl)
                    .addComponent(nombre_lbl)
                    .addComponent(fecha_nac_lbl)
                    .addComponent(sexo_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_reg_lbl)
                    .addComponent(id_lbl))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nombre_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(apellidos_txt)
                        .addComponent(fecha_nac_txt)
                        .addComponent(sexo_cmbbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fecha_reg_txt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peso_lbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(altura_lbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(altura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(nivel_act_fis_lbl)
                            .addGap(18, 18, 18)
                            .addComponent(nivel_act_fis_cmbbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(agregar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(372, 372, 372))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(agregar_pac_lbl)
                        .addGap(472, 472, 472))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(793, Short.MAX_VALUE)
                    .addComponent(peso_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(102, 102, 102)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(id_lbl)
                                .addGap(29, 29, 29)
                                .addComponent(nombre_lbl)
                                .addGap(18, 18, 18)
                                .addComponent(apellidos_lbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(id_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombre_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellidos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_nac_lbl)
                            .addComponent(fecha_nac_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexo_lbl)
                            .addComponent(sexo_cmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fecha_reg_lbl)
                            .addComponent(fecha_reg_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(agregar_pac_lbl)
                        .addGap(67, 67, 67)
                        .addComponent(peso_lbl)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(altura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altura_lbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nivel_act_fis_lbl)
                            .addComponent(nivel_act_fis_cmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(agregar_btn)
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(peso_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(299, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altura_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altura_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altura_txtActionPerformed

    private void agregar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_btnActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        String identificacion = id_txt1.getText().trim(); 
        String nombre = nombre_txt1.getText().trim();
        String apellidos = apellidos_txt.getText().trim();
        String fecha_nac = fecha_nac_txt.getText().trim();
        String sexo = sexo_cmbbox.getSelectedItem().toString().trim(); 
        //char sexo_char = sexo.charAt(0);
        String fecha_reg = fecha_reg_txt.getText().trim(); 
        String peso = peso_txt1.getText().trim(); 
        BigDecimal pesoBD = new BigDecimal(peso);
        String altura = altura_txt.getText().trim(); 
        BigDecimal alturaBD = new BigDecimal(altura);
        
        
        
        
        Paciente paciente = new Paciente(identificacion, nombre, apellidos, fecha_nac, sexo, fecha_reg);
        
        try {
            
            if ((identificacion.equalsIgnoreCase("")) || 
                    (nombre.equalsIgnoreCase("")) || 
                    (apellidos.equalsIgnoreCase("")) || 
                    (fecha_nac.equalsIgnoreCase("")) || 
                    (sexo.equalsIgnoreCase("")) || 
                    (fecha_reg.equalsIgnoreCase("")) || 
                    (peso.equalsIgnoreCase("")) || 
                    (altura.equalsIgnoreCase(""))) {

                    JOptionPane.showMessageDialog(null, 
                        "Revise los campos de texto, no se puede guardar datos con campos incompletos");
                    

                }else{
                DatabaseManager.insertarPaciente(paciente);
                
                double imc = DatabaseManager.calcularIMC(Double.parseDouble(peso), Double.parseDouble(altura));
                String categoria_imc = DatabaseManager.clasificarIMC(imc);
                String recomendaciones = DatabaseManager.recomendacionesPorIMC(imc);
                String nivel_actividad_fisica = DatabaseManager.clasificarNivelActividadFisica(imc);
                
                Evaluacion eval = new Evaluacion(paciente.getIdentificacion(), rol, fecha_reg, pesoBD, alturaBD, nivel_actividad_fisica, BigDecimal.valueOf(imc), categoria_imc, recomendaciones);
                
                
                DatabaseManager.insertarEvaluacion(eval);
                JOptionPane.showMessageDialog(null, 
                        "Se ha guardado el paciente con exito!");
                
                id_txt1.setText("");
                nombre_txt1.setText("");
                apellidos_txt.setText("");
                fecha_nac_txt.setText("");
                sexo_cmbbox.setSelectedIndex(0);
                fecha_reg_txt.setText("");
                peso_txt1.setText("");
                altura_txt.setText("");
                
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_agregar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Agrega_paciente_vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_btn;
    private javax.swing.JLabel agregar_pac_lbl;
    private javax.swing.JLabel altura_lbl;
    private javax.swing.JTextField altura_txt;
    private javax.swing.JLabel apellidos_lbl;
    private javax.swing.JTextField apellidos_txt;
    private javax.swing.JLabel fecha_nac_lbl;
    private javax.swing.JFormattedTextField fecha_nac_txt;
    private javax.swing.JLabel fecha_reg_lbl;
    private javax.swing.JFormattedTextField fecha_reg_txt;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JTextField id_txt1;
    private javax.swing.JComboBox<String> nivel_act_fis_cmbbox;
    private javax.swing.JLabel nivel_act_fis_lbl;
    private javax.swing.JLabel nombre_lbl;
    private javax.swing.JTextField nombre_txt1;
    private javax.swing.JLabel peso_lbl;
    private javax.swing.JTextField peso_txt1;
    private javax.swing.JComboBox<String> sexo_cmbbox;
    private javax.swing.JLabel sexo_lbl;
    // End of variables declaration//GEN-END:variables
    public int rol; 
}
