/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ac.cr.uned.nutrimind.vistas;

import ac.cr.uned.nutrimind.modelos.Evaluacion;
import ac.cr.uned.nutrimind.modelos.Paciente;
import ac.cr.uned.nutrimind.resources.DatabaseManager;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class Evaluar_paciente_vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Evaluar_paciente_vista.class.getName());

    /**
     * Creates new form Evaluar_paciente_vista
     */
    public Evaluar_paciente_vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evac_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        buscar_btn = new javax.swing.JButton();
        nutri_lbl = new javax.swing.JLabel();
        nutri_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fecha_evac_txt = new javax.swing.JFormattedTextField();
        peso_lbl = new javax.swing.JLabel();
        peso_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        altura_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nivel_act_fis_cmbbox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        info_txtarea = new javax.swing.JTextArea();
        guardar_evac_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        evac_lbl.setText("Evaluación de Paciente");

        jLabel2.setText("Identificación: ");

        buscar_btn.setText("Buscar");
        buscar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_btnActionPerformed(evt);
            }
        });

        nutri_lbl.setText("Nutricionista: ");

        jLabel1.setText("Fecha Evaluación: ");

        fecha_evac_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        peso_lbl.setText("Peso (kg):");

        jLabel3.setText("Altura (cm): ");

        jLabel4.setText("Nivel Actividad Física: ");

        nivel_act_fis_cmbbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentario", "Moderadamente Activo", "Muy Activo", " " }));

        info_txtarea.setColumns(20);
        info_txtarea.setRows(5);
        jScrollPane1.setViewportView(info_txtarea);

        guardar_evac_btn.setText("Guardar Evaluación");
        guardar_evac_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_evac_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nutri_lbl)
                            .addComponent(jLabel1)
                            .addComponent(peso_lbl)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_txt)
                            .addComponent(nutri_txt)
                            .addComponent(fecha_evac_txt)
                            .addComponent(peso_txt)
                            .addComponent(altura_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)
                        .addComponent(nivel_act_fis_cmbbox, 0, 174, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(buscar_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(evac_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(guardar_evac_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(evac_lbl)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_btn))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nutri_lbl)
                            .addComponent(nutri_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fecha_evac_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(peso_lbl)
                            .addComponent(peso_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(altura_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nivel_act_fis_cmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(guardar_evac_btn)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardar_evac_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_evac_btnActionPerformed
        // TODO add your handling code here:
        
        String nutri_id = nutri_txt.getText().trim();
        double nutri_id_double = Double.parseDouble(nutri_id);
        BigDecimal nutri_id_DB = BigDecimal.valueOf(nutri_id_double);
        
        String fecha_eval = fecha_evac_txt.getText().trim();
        String peso = peso_txt.getText().trim();
        String altura = altura_txt.getText().trim();
        
        BigDecimal pesoBD = new BigDecimal(peso);
        
        BigDecimal alturaBD = new BigDecimal(altura);
        
        String nivel_act = nivel_act_fis_cmbbox.getSelectedItem().toString();
        
        
        double imc = DatabaseManager.calcularIMC(Double.parseDouble(peso), Double.parseDouble(altura));
        String categoria_imc = DatabaseManager.clasificarIMC(imc);
        String recomendaciones = DatabaseManager.recomendacionesPorIMC(imc);
        String nivel_actividad_fisica = nivel_act_fis_cmbbox.getSelectedItem().toString();
        
        Evaluacion eval = new Evaluacion(id_txt.getText().trim(), 2, fecha_eval, pesoBD, alturaBD, nivel_actividad_fisica, BigDecimal.valueOf(imc), categoria_imc, recomendaciones);
        
        
        
        try{
            DatabaseManager.insertarEvaluacion(eval);
            JOptionPane.showMessageDialog(null, 
                        "Evaluación guardada!");
            
            String texto = "IMC: " + String.valueOf(imc) + "\n" + 
                "Categoría IMC: " + categoria_imc + "\n" + 
                "Recomendaciones: " + recomendaciones + "\n" + 
                "Nivel de actividad física: " + nivel_actividad_fisica + "\n";
        
            info_txtarea.setText(texto);
            
            id_txt.setText("");
            nutri_txt.setText("");
            fecha_evac_txt.setText("");
            peso_txt.setText("");
            altura_txt.setText("");

        }catch (Exception ex){
            ex.printStackTrace();
        }
 
        
    }//GEN-LAST:event_guardar_evac_btnActionPerformed

    private void buscar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_btnActionPerformed
        // TODO add your handling code here:
        
        String identificacion = id_txt.getText().trim();
        Paciente paciente = new Paciente();
        try{
            paciente =  DatabaseManager.obtenerPacientePorIdentificacion(identificacion);
            if(!paciente.equals(null)){
                JOptionPane.showMessageDialog(null, 
                        "Paciente encontrado!");
            }else{
                JOptionPane.showMessageDialog(null, 
                        "Paciente no encontrado, registre al paciente primero");
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_buscar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Evaluar_paciente_vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura_txt;
    private javax.swing.JButton buscar_btn;
    private javax.swing.JLabel evac_lbl;
    private javax.swing.JFormattedTextField fecha_evac_txt;
    private javax.swing.JButton guardar_evac_btn;
    private javax.swing.JTextField id_txt;
    private javax.swing.JTextArea info_txtarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> nivel_act_fis_cmbbox;
    private javax.swing.JLabel nutri_lbl;
    private javax.swing.JTextField nutri_txt;
    private javax.swing.JLabel peso_lbl;
    private javax.swing.JTextField peso_txt;
    // End of variables declaration//GEN-END:variables
}
