/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ac.cr.uned.nutrimind.vistas;

import ac.cr.uned.nutrimind.modelos.Usuario;
import ac.cr.uned.nutrimind.resources.DatabaseManager;
import java.awt.Image;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 */
public class Login_vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login_vista.class.getName());

    /**
     * Creates new form Login_vista
     */
    public Login_vista() {
        initComponents();
        
        
        ImageIcon label_icon = new ImageIcon(getClass().getResource("/ac/cr/uned/nutrimind/resources/nutrimind_logo.png"));
        Image scaledImage = label_icon.getImage().getScaledInstance(
        nutrimind_lbl.getWidth(), 
        nutrimind_lbl.getHeight(), 
        Image.SCALE_SMOOTH
    );
        nutrimind_lbl.setIcon(new ImageIcon(scaledImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_lbl = new javax.swing.JLabel();
        usuario_lbl = new javax.swing.JLabel();
        contrasena_lbl = new javax.swing.JLabel();
        usuario_txtf = new javax.swing.JTextField();
        contrasena_txtf = new javax.swing.JPasswordField();
        nutrimind_lbl = new javax.swing.JLabel();
        entrar_btn = new javax.swing.JButton();
        crear_cuenta_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        login_lbl.setText("Log in");

        usuario_lbl.setText("Usuario:");

        contrasena_lbl.setText("Contraseña: ");

        nutrimind_lbl.setText("jLabel1");

        entrar_btn.setText("Entrar");
        entrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar_btnActionPerformed(evt);
            }
        });

        crear_cuenta_btn.setText("Crear Cuenta");
        crear_cuenta_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_cuenta_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(nutrimind_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuario_lbl)
                    .addComponent(contrasena_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(crear_cuenta_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(entrar_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(login_lbl)
                    .addComponent(usuario_txtf)
                    .addComponent(contrasena_txtf))
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(login_lbl)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuario_lbl)
                            .addComponent(usuario_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contrasena_lbl)
                            .addComponent(contrasena_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(entrar_btn)
                        .addGap(34, 34, 34)
                        .addComponent(crear_cuenta_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(nutrimind_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar_btnActionPerformed
        // TODO add your handling code here:
        
        String usuario = usuario_txtf.getText().trim(); 
        
        char[] passwordChars = contrasena_txtf.getPassword();
        String contrasena  = new String(passwordChars);
 
        
        Usuario user = new Usuario(usuario, contrasena);
        
        
        try{
            boolean confirmacion = DatabaseManager.autenticarUsuario(user);
            if(confirmacion){
                String rol_usuario = DatabaseManager.obtenerRolPorUsuario(user.getUsuario());
                
                if(rol_usuario.equalsIgnoreCase("ADMIN")){
                    dispose();
                    SwingUtilities.invokeLater(() -> {
            
                    Admin_vista adminWindow = new Admin_vista();
                    adminWindow.setLocationRelativeTo(null);
                    adminWindow.setResizable(false);
                    adminWindow.setVisible(true);
                });
                   
                }else if(rol_usuario.equalsIgnoreCase("PROF")){
                    dispose();
                    SwingUtilities.invokeLater(() -> {
                    
                    int rol = 2;
                        try {
                            rol = DatabaseManager.obtenerRolIdPorUsuario(user.getUsuario());
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                        
                    Nutricionista_vista nutriWindow = new Nutricionista_vista(rol);
                    nutriWindow.setLocationRelativeTo(null);
                    nutriWindow.setResizable(false);
                    nutriWindow.setVisible(true);
                });
                    
                }else{
                    dispose();
                    SwingUtilities.invokeLater(() -> {
            
                    Asistente_vista asisWindow = new Asistente_vista();
                    asisWindow.setLocationRelativeTo(null);
                    asisWindow.setResizable(false);
                    asisWindow.setVisible(true);
                });
                    
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo ingresar, hubo un error, verifique que el usuario exista");
                usuario_txtf.setText("");
                contrasena_txtf.setText("");
            }
            
            
        }catch (Exception ex){
            ex.printStackTrace();
        }
         
    }//GEN-LAST:event_entrar_btnActionPerformed

    private void crear_cuenta_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_cuenta_btnActionPerformed
        // TODO add your handling code here:
        
        SwingUtilities.invokeLater(() -> {
            
            Crear_cuenta_vista crearCuentaWindow = new Crear_cuenta_vista();
            crearCuentaWindow.setLocationRelativeTo(null);
            crearCuentaWindow.setResizable(false);
            crearCuentaWindow.setVisible(true);
        });
    }//GEN-LAST:event_crear_cuenta_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login_vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contrasena_lbl;
    private javax.swing.JPasswordField contrasena_txtf;
    private javax.swing.JButton crear_cuenta_btn;
    private javax.swing.JButton entrar_btn;
    private javax.swing.JLabel login_lbl;
    private javax.swing.JLabel nutrimind_lbl;
    private javax.swing.JLabel usuario_lbl;
    private javax.swing.JTextField usuario_txtf;
    // End of variables declaration//GEN-END:variables
}
