/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ac.cr.uned.nutrimind.vistas;

import ac.cr.uned.nutrimind.modelos.Paciente;
import ac.cr.uned.nutrimind.modelos.PlanAlimentacion;
import ac.cr.uned.nutrimind.resources.DatabaseManager;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 *
 */
public class Planes_alimentacion_vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Planes_alimentacion_vista.class.getName());

    /**
     * Creates new form Planes_alimentacion_vista
     */
    public Planes_alimentacion_vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plan_alim_lbl = new javax.swing.JLabel();
        id_lbl = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        buscar_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fecha_creacion_txt = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        fecha_final_txt = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        nutri_txt = new javax.swing.JTextField();
        plan_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        plan_txtarea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        carb_checkbox = new javax.swing.JCheckBox();
        prot_checkbox = new javax.swing.JCheckBox();
        grasa_checkbox = new javax.swing.JCheckBox();
        comidas_dia_lbl = new javax.swing.JLabel();
        comidas_dia_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alimentos_rec_txtarea = new javax.swing.JTextArea();
        observ_lbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        observ_txtarea = new javax.swing.JTextArea();
        guardar_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plan_alim_lbl.setText("Generación de Planes de Alimentación");

        id_lbl.setText("Identificación: ");

        buscar_btn.setText("Buscar");
        buscar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha Creación: ");

        fecha_creacion_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel2.setText("Fecha Final: ");

        fecha_final_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel3.setText("Nutricionista: ");

        plan_lbl.setText("Plan Nutricional: ");

        plan_txtarea.setColumns(20);
        plan_txtarea.setRows(5);
        jScrollPane1.setViewportView(plan_txtarea);

        jLabel4.setText("Macronutrientes: ");

        carb_checkbox.setText("Carbohidratos");

        prot_checkbox.setText("Proteínas");

        grasa_checkbox.setText("Grasas");

        comidas_dia_lbl.setText("Comidas al día: ");

        jLabel5.setText("Alimentos Recomendados: ");

        alimentos_rec_txtarea.setColumns(20);
        alimentos_rec_txtarea.setRows(5);
        jScrollPane2.setViewportView(alimentos_rec_txtarea);

        observ_lbl.setText("Observaciones: ");

        observ_txtarea.setColumns(20);
        observ_txtarea.setRows(5);
        jScrollPane3.setViewportView(observ_txtarea);

        guardar_btn.setText("Guardar Plan");
        guardar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_lbl)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(plan_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id_txt)
                                    .addComponent(fecha_creacion_txt)
                                    .addComponent(fecha_final_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(nutri_txt))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(buscar_btn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(comidas_dia_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(prot_checkbox)
                                                    .addComponent(carb_checkbox)
                                                    .addComponent(grasa_checkbox)
                                                    .addComponent(comidas_dia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(observ_lbl))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plan_alim_lbl)
                                        .addGap(278, 278, 278))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(guardar_btn)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(plan_alim_lbl)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_lbl)
                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_btn))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fecha_creacion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(carb_checkbox))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fecha_final_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prot_checkbox))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nutri_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grasa_checkbox))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plan_lbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comidas_dia_lbl)
                            .addComponent(comidas_dia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(observ_lbl)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(guardar_btn)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_btnActionPerformed
        // TODO add your handling code here:
        
        String fecha_creacion = fecha_creacion_txt.getText().trim();
        String fecha_final = fecha_final_txt.getText().trim();
        String nutricionista = nutri_txt.getText().trim();
        String plan_nutricional = plan_txtarea.getText();
        StringBuilder macronutrientes = new StringBuilder();
        
        if(carb_checkbox.isSelected()){
            macronutrientes.append(carb_checkbox.getText()).append(" ");
            
        }
        
        if(prot_checkbox.isSelected()){
            macronutrientes.append(prot_checkbox.getText()).append(" ");
            
        }
        
        if(grasa_checkbox.isSelected()){
            macronutrientes.append(grasa_checkbox.getText()).append(" ");
        }
        
        String macronutrientes_str = macronutrientes.toString();
        
        
        String comidas_dia = comidas_dia_txt.getText().trim();
        BigDecimal comidas_dia_BD = new BigDecimal(comidas_dia);
        
        String alimentos_rec = alimentos_rec_txtarea.getText().trim();
        String observaciones = observ_txtarea.getText().trim(); 
        
        PlanAlimentacion plan = new PlanAlimentacion(id_txt.getText().trim(), Integer.parseInt(nutricionista), fecha_creacion, fecha_final, plan_nutricional, macronutrientes_str, Integer.parseInt(comidas_dia), alimentos_rec, observaciones);
                
        try{
            DatabaseManager.insertarPlan(plan);
            JOptionPane.showMessageDialog(null, 
                        "Plan asociado con exito!");
        }catch (Exception ex){
            ex.printStackTrace();
        }
        
                
                
    }//GEN-LAST:event_guardar_btnActionPerformed

    private void buscar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_btnActionPerformed

        // TODO add your handling code here:
        String identificacion = id_txt.getText().trim();
        Paciente paciente = new Paciente();
        try{
            paciente =  DatabaseManager.obtenerPacientePorIdentificacion(identificacion);
            if(!paciente.equals(null)){
                JOptionPane.showMessageDialog(null, 
                        "Paciente encontrado!");
            }else{
                JOptionPane.showMessageDialog(null, 
                        "Paciente no encontrado, registre al paciente primero");
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buscar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Planes_alimentacion_vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alimentos_rec_txtarea;
    private javax.swing.JButton buscar_btn;
    private javax.swing.JCheckBox carb_checkbox;
    private javax.swing.JLabel comidas_dia_lbl;
    private javax.swing.JTextField comidas_dia_txt;
    private javax.swing.JFormattedTextField fecha_creacion_txt;
    private javax.swing.JFormattedTextField fecha_final_txt;
    private javax.swing.JCheckBox grasa_checkbox;
    private javax.swing.JButton guardar_btn;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nutri_txt;
    private javax.swing.JLabel observ_lbl;
    private javax.swing.JTextArea observ_txtarea;
    private javax.swing.JLabel plan_alim_lbl;
    private javax.swing.JLabel plan_lbl;
    private javax.swing.JTextArea plan_txtarea;
    private javax.swing.JCheckBox prot_checkbox;
    // End of variables declaration//GEN-END:variables
}
